### ISSUE TITLE
"with" option fail when use the pgloader cli 

### ISSUE THREAD

**Issue by thomasLeclaire** [dimitri/pgloader#1055]
Hi!

  - [ ] pgloader --version  
    ```
pgloader version "3.6.1"   (installed through brew on mac Catalina)
compiled with SBCL 1.5.8
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    no but didn't saw any commit related.

  - [ ] did you search for other similar issues?
yes 

  - [ ] how can I reproduce the bug?

  1. show what you did : 
try to use the pgloader cli with options "--with xxx"
pgloader --verbose --debug --type csv --encoding="ISO-8859-1" ./xxx.csv 'postgresql://user:pass@0.0.0.0:54321/db?tablename=xxx'  is perfectly working

pgloader --verbose --debug --type csv --with "truncate" --encoding="ISO-8859-1" ./xxx.csv 'postgresql://user:pass@0.0.0.0:54321/db?tablename=xxx'  is not working with error below

  2. show the result you got : 
`#<CLOSURE (LAMBDA (COMMAND-LINE-ARGUMENTS::VALUE)
            :IN
            COMMAND-LINE-ARGUMENTS::MAKE-OPTION-ACTION) {1004D9E15B}> fell through ETYPECASE expression.
Wanted one of (NULL KEYWORD SYMBOL CONS).
`

  3. explain how the result is not what you expected.
the tool is perfectly working if I use the standard command file and call it with option truncate or other WITH ones.
the cli is working perfectly if I don't specify the --with option, but as soon I add it it's not working anymore, tried truncate, csv header, skipheader,.. no one is working.

Tried  also the tutorial commands here : https://pgloader.readthedocs.io/en/latest/quickstart.html which fail also with same error.

**Comment by thomasLeclaire** [comment]
FYI, just did a test from an Ubuntu 18.04 : 
the default package available on apt is only pgloader 3.5.2, and I don't have the issue. 

I tryed to do a manual build (I have a lot of LISP issues related to duplicate naming), but manually manage all the errors, I can get this build  
pgloader version "3.6.26cc9ca"
compiled with SBCL 1.4.5.debian
and exact same behavior than my mac brew installation : the cli is not working with option with but no prob if I use a dedicated command file.


regards

**Comment by BasileNouvellet** [comment]
Is there any update about this issue?

**Comment by svantevonerichsen6906** [comment]
I feel quite sure that the fix of command-line-arguments mentioned above should fix this issue.  So, we need the new version of that.

- You could for now compile yourself with a local checkout of command-line-arguments (https://github.com/fare/command-line-arguments).

- As soon as the new version is in Quicklisp, you just need to update that and compile.

- Hopefully the next release will also have it.

**Comment by dimitri** [comment]
Do we know if release 3.6.2 is good now?

**Comment by bushd0c** [comment]
pgloader version "3.6.2"
compiled with SBCL 2.0.2
(Homebrew/Mac OS X 10.15.5)

As soon as I use the --with option (e.g. like: --with "snake_case identifiers")  I get the

#<CLOSURE (LAMBDA (COMMAND-LINE-ARGUMENTS::VALUE)
            :IN
            COMMAND-LINE-ARGUMENTS::MAKE-OPTION-ACTION) {1004DBA64B}> fell through ETYPECASE expression.
Wanted one of (NULL KEYWORD SYMBOL CONS).

**Comment by ovisuru** [comment]
Any update on this issue? I also use the following version and still facing this issue.

pgloader version "3.6.2"
compiled with SBCL 2.0.2

**Comment by chrisnoden** [comment]
This error also appears if you use the `--set` option:
`pgloader --type csv --set "search_path='myschema'" "data.csv" "postgres://username:secret@db-host:5432/mydb?tablename=mytable"`

Tried several variations of quoting the value for --set - no joy. I am on a mac so this uses `zsh` but I also tried in bash.

```
#<CLOSURE (LAMBDA (COMMAND-LINE-ARGUMENTS::VALUE)
            :IN
            COMMAND-LINE-ARGUMENTS::MAKE-OPTION-ACTION) {1004C7F98B}> fell through ETYPECASE expression.
Wanted one of (NULL KEYWORD SYMBOL CONS).
```

pgloader version "3.6.2"
compiled with SBCL 2.0.11
on MacOS 11.2
installed with HomeBrew

**Comment by jordanebordet** [comment]
> I feel quite sure that the fix of command-line-arguments mentioned above should fix this issue. So, we need the new version of that.
> 
> * You could for now compile yourself with a local checkout of command-line-arguments (https://github.com/fare/command-line-arguments).
> * As soon as the new version is in Quicklisp, you just need to update that and compile.
> * Hopefully the next release will also have it.

 I have exactly the same problem with version 3.6.2 on centos, install from yum postgresql repository. I'm a bit lost with the compilation process.
Can you explain me with more details how to fix it. I cannot wait for 3.6.3 release. Thanks you so much to help me.

**Comment by mjmohammadi1** [comment]
Hi @dimitri ,
Any updates on this issue ? I'm facing the same issue as others :
```pgloader version "3.6.2"```
```compiled with SBCL 2.0.11```
on MacOS 11.4
installed with HomeBrew

**Comment by dimitri** [comment]
This issue is fixed in **pgloader v4** (Clojure/JVM rewrite), tracked in PR #1705.

pgloader v4 is a drop-in replacement distributed as a single self-contained JAR (Java 21+). You can try it with the evergreen pre-release build:

```
curl -L -o pgloader.jar https://github.com/dimitri/pgloader/releases/download/v4-dev/pgloader.jar
java -jar pgloader.jar --version
```

Closing as fixed in v4.
