### ISSUE TITLE
"create no indexes" not honored

### ISSUE THREAD

**Issue by daledude** [dimitri/pgloader#539]
Even with "create no indexes" pgloader still tries to create indexes.

```
load database
     from      mysql://localhost/ad
     into postgresql://localhost:5432/ad

 WITH include drop,
      create tables,
      create no indexes,
      no truncate,
      reset sequences,
      no foreign keys,
      quote identifiers

 SET search_path to 'sakila'

 CAST type datetime to timestamptz using zero-dates-to-null,
      type datetime when default '0000-00-00 00:00:00' to timestamp using zero-dates-to-null,
      type datetime to timestamp drop default drop not null using zero-dates-to-null,
      type timestamp to timestamp drop default drop not null using zero-dates-to-null

 ALTER SCHEMA 'ad' RENAME TO 'sakila'

 INCLUDING ONLY TABLE NAMES MATCHING 'ia'
 ;
```

------------------------------

```
2017-04-24T19:42:05.056000-07:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-04-24T19:42:05.059000-07:00 LOG Data errors in '/tmp/pgloader/'
2017-04-24T19:42:05.060000-07:00 LOG Parsing commands from file #P"/home/d/pgloader/d.load"
2017-04-24T19:42:05.672000-07:00 ERROR Database error 42P16: UNIQUE index must contain all columns in the distribution key of relation "ia"
QUERY: CREATE UNIQUE INDEX "idx_107363_ac" ON sakila."ia" ("ac");
```

**Comment by dimitri** [comment]
I think this was fixed in https://github.com/dimitri/pgloader/commit/96b2af6b2a2b163f7e9e3c0ba744da1733b23979 and https://github.com/dimitri/pgloader/commit/1023577f504fdcff288cf289d83ec7c9dd0a49f7 ; can you report the version of pgloader you are using and try again, building from sources or using a recent docker image?

**Comment by daledude** [comment]
Sorry, the version would have been useful. Compiling from master works.Testing this with Greenplum but between the indexes needing special care due to DISTRIBUTION and now this db not supporting "IF EXISTS" for DROP/CREATE I'll need to check the alternatives that are in languages I better understand.

Thank you.

**Comment by dimitri** [comment]
Can you report what `SELECT version()` against your target database reports? We don't have any conditional feature set yet, but I think it's time to think about that, and your use case is a good one to start on this path.

**Comment by sunbing81** [comment]
strange, I still have the issue that pgloader just ignores 'create no indexes' option.

pgloader is compiled from source against the latest commit `3c4e64e`.

Config:
```
load database
  from    mysql://root@localhost/test
  into   postgresql:///postgres

WITH create no indexes

CAST
  type char    when (= precision 0) drop typemod,
  type varchar when (= precision 0) drop typemod

INCLUDING ONLY TABLE NAMES MATCHING ~[zhuoyue]
ALTER SCHEMA 'test' RENAME TO 'staging'
;
```
 
Summary:
```             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        fetch meta data          4          4          0          0.110s
       Create SQL Types          0          0          0          0.014s        
          Create tables          2          2          0          0.072s        
         Set Table OIDs          1          1          0          0.017s       
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        staging.zhuoyue     200983     200983          0          2.447s     2.124s    1.474s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          3          3          0          2.441s
 Index Build Completion          3          3          0          4.398s
         Create Indexes          3          3          0          5.702s
        Reset Sequences          0          1          0          0.099s
           Primary Keys          1          1          0          0.052s
    Create Foreign Keys          0          0          0          0.000s
        Create Triggers          0          0          0          0.006s
       Install Comments          0          0          0          0.000s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time     200983     200983          0          7.813s     2.124s    1.474s
```

Thanks!

**Comment by dimitri** [comment]
Add `include no drop` to enable the behaviour you want, if I understand correctly. I will need to simplify the number of schema handling related switches a lot.

**Comment by sunbing81** [comment]
Tried `include no drop, create no indexes`, but pgloader keeps to create the indexes.

**Comment by dimitri** [comment]
So should be good now, can you try again?

**Comment by sunbing81** [comment]
Thanks, `create no indexes` works as expected now.
