### ISSUE TITLE
Mysql to PG only first cast?

### ISSUE THREAD

**Issue by eMerzh** [dimitri/pgloader#811]
- [x] pgloader --version
  ```pgloader version "3.5.1~devel"
compiled with SBCL 1.4.7
 ```
from homebrew

```
load database
    FROM mysql://u:p@yop/yop
    INTO postgresql://yop@localhost:5432/yop
WITH
    schema only, quote identifiers, batch rows = 5000, batch concurrency = 2
    CAST type datetime to timestamp drop default drop not null using zero-dates-to-null

INCLUDING ONLY TABLE NAMES MATCHING 'domain_filter';
```

the domain_filter table look like this : 
```sql
CREATE TABLE `domain_filter` (
  `id` binary(16) NOT NULL ,
  `type` varchar(50) NOT NULL ,
  `value` json DEFAULT NULL ,
  `negated` tinyint(1) NOT NULL DEFAULT '0' ,
  `report_id` varbinary(255) NOT NULL ,
  `query_id` varchar(255) NOT NULL ,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP ,
  `updated_by` varbinary(255) DEFAULT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `domain_filter_unq` (`report_id`,`query_id`,`type`),
  KEY `domain_filter` (`type`),
  CONSTRAINT `domain_filter_ibfk_1` FOREIGN KEY (`type`) REFERENCES `domain_filter_type` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;
```

but when i try to launch it, it says:
```
...
2018-06-29T08:57:17.160000+01:00 ERROR Database error 42704: type "datetime" does not exist
QUERY: CREATE TABLE "ratigan"."domain_filter"
(
  "id"         bytea not null,
  "type"       varchar(50) not null,
  "value"      json,
  "negated"    boolean not null default 'f',
  "report_id"  bytea not null,
  "query_id"   varchar(255) not null,
  "created_at" timestamp,
  "updated_at" datetime,
  "updated_by" bytea
);
2018-06-29T08:57:17.160000+01:00 FATAL Failed to create the schema, see above.
2018-06-29T08:57:17.160000+01:00 LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data          0          4                     0.829s
   Create Schemas          0          0                     0.002s
 Create SQL Types          0          0                     0.006s
    Create tables          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
```

strengly updated_at isn't casted... 
any idea?

**Comment by dimitri** [comment]
This is a bug I introduced recently, and fixed in https://github.com/dimitri/pgloader/commit/05b4c7c9782dd15e7422a1e8e52753ba493384b6. Please try a fresh version compiled from git's master branch and you should be good!

**Comment by eMerzh** [comment]
Oh ok cool, thanks for the quick reply!
i'll try to upgrade brew's version 👍

**Comment by eMerzh** [comment]
do you plan a release, soonish ?

**Comment by eMerzh** [comment]
thanks for the release and the update 👍 

but it seems the issue is still there ?
```$ pgloader mysql.load
2018-07-05T14:32:07.557000+01:00 ERROR Database error 42704: type "datetime" does not exist
QUERY: CREATE TABLE "brol"."domain_filter"
(
  "id"         bytea not null,
  "type"       varchar(50) not null,
  "value"      json,
  "negated"    boolean not null default 'f',
  "report_id"  bytea not null,
  "query_id"   varchar(255) not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" datetime,
  "updated_by" bytea
);
2018-07-05T14:32:07.557000+01:00 FATAL Failed to create the schema, see above.
2018-07-05T14:32:07.560000+01:00 LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data          0          4                     2.352s
   Create Schemas          0          0                     0.002s
 Create SQL Types          0          0                     0.006s
    Create tables          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------

 $ pgloader --version
pgloader version "3.5.2"
compiled with SBCL 1.4.9```

**Comment by dimitri** [comment]
Try removing your CAST clause, which is a default clause anyway?

**Comment by eMerzh** [comment]
my conf file is now:
```
load database
    FROM mysql://brol@localhost/truc
    INTO postgresql://xx@localhost:5432/xx

SET PostgreSQL PARAMETERS search_path to 'truc, public, "$user"'

INCLUDING ONLY TABLE NAMES MATCHING 'domain_filter'
;
```
so there is no cast ...

and result is still : 

```
2018-07-06T13:09:48.995000+01:00 ERROR Database error 42704: type "datetime" does not exist
QUERY: CREATE TABLE xx.domain_filter
(
  id         bytea not null,
  type       varchar(50) not null,
  value      json,
  negated    boolean not null default 'f',
  report_id  bytea not null,
  query_id   varchar(255) not null,
  created_at timestamptz not null default CURRENT_TIMESTAMP,
  updated_at datetime,
  updated_by bytea
);
```

**Comment by dimitri** [comment]
I could reproduce the bug here and then fix it. We were missing casting rules for dates with _on update current timestamp_ which would be _nullable_, as it's the case in your `updated_at` column:

``` sql
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP ,
```
